NEW: CI creates build_info.json for runtime method build_info
tonlabs/TON-SDK pull request #184
Opened 2020-10-02 11:39 UTC by g9d

2020-10-05 08:24 UTC, melsomino requested changes
see comments

2020-10-05 08:24 UTC, melsomino commented on ton_client/client/src/build_info.rs
> +pub(crate) fn register(handlers: &mut DispatchTable) {
We can't read files in runtime.
The json content must be embedded into rs source as a string constant.

2020-10-05 10:16 UTC, melsomino requested changes
return empty map `{}` instead of `null` if file can't read from disk

2020-10-05 13:57 UTC, melsomino approved these changes

2020-10-07 10:38 UTC, AlexeyVavilin approved these changes

2020-10-08 13:08 UTC, merged