small fixes
tonlabs/TON-SDK pull request #311
Opened 2021-01-19 08:17 UTC by elasticLove1

2021-01-20 10:17 UTC, melsomino requested changes
see comments

2021-01-20 10:17 UTC, melsomino commented on api/derive/src/utils.rs
> +                description.push_str("\n");
description.push_str(" ");

2021-01-20 12:26 UTC, d3p approved these changes

2021-01-22 07:43 UTC, d3p approved these changes

2021-01-22 07:44 UTC, melsomino approved these changes

2021-01-22 07:45 UTC, merged