Debot interfaces update
tonlabs/TON-SDK pull request #355
Opened 2021-02-25 14:34 UTC by mikhailUshakoff

Add three unstable functions to debot sdk interface. they are proxy to sdk functions:
nacl_box
nacl_box_open
nacl_box_keypair_from_secret_key

Add debot system interface for hex encoding and decoding.

Update tests for internal interfaces.

2021-02-25 15:23 UTC, AlexeyVavilin approved these changes

2021-02-26 09:29 UTC, Keshoid requested changes

2021-02-26 09:29 UTC, Keshoid commented on ton_client/src/debot/hex_interface.rs
> +		//let encoded = base64::encode(&data_to_encode);
Please, remove unused code.

2021-02-26 09:29 UTC, Keshoid commented on ton_client/src/debot/hex_interface.rs
> +            hex::decode(&str_to_decode).map_err(|e| format!("invalid base64: {}", e))?;
Fix error message: `invalid base64`. It is not a base64, right?

2021-02-26 09:29 UTC, Keshoid commented on ton_client/src/debot/sdk_interface.rs
> +        let decrypted = base64::encode(&hex::decode(&get_arg(args, "decrypted")?).unwrap());
Use `map_err()?` instead of `unwrap()`, ok?

2021-02-26 09:29 UTC, Keshoid commented on ton_client/src/debot/sdk_interface.rs
> +                their_public: format!("{:064x}", public),
You can write
```
ParamsOfNaclBox {
   decrypted,
   nonce,
 ....
 }
```
If name of var and field are the same.

2021-02-26 09:29 UTC, Keshoid commented on ton_client/src/debot/sdk_interface.rs
> +        Ok((answer_id, json!({ "decrypted": hex::encode(&base64::decode(&result.decrypted).unwrap()) })))
Please, handle `unwrap()`.

2021-03-01 10:38 UTC, Keshoid approved these changes
LGTM

2021-03-01 14:42 UTC, merged