Dengine: support of signing box handles
tonlabs/TON-SDK pull request #404
Opened 2021-05-17 14:45 UTC by Keshoid

- signing messages with signing box handles returned from debots.
    - return any sdk errors to debot in case of external calls.
    - defining signing box handle used to sign message in approve callback.

2021-05-17 17:39 UTC, melsomino requested changes

2021-05-17 19:40 UTC, Keshoid commented on ton_client/src/debot/calltype.rs
> +    sign_box_handle: Option<SigningBoxHandle>,
Ok.

2021-05-17 19:40 UTC, Keshoid commented on ton_client/src/debot/activity.rs
> +        sbhandle: u32,
Ok

2021-05-18 06:34 UTC, melsomino approved these changes

2021-05-18 07:08 UTC, merged